name: 'Coiled Login'
description: 'GitHub Action to login to Coiled'
author: 'Coiled'

branding:
  icon: 'log-in'
  color: 'blue'

inputs:
  token:
    description: "Coiled user API token. Required. You can create a token at https://cloud.coiled.io/profile?createTokenDialog=1"
    required: true
  workspace:
    description: "Coiled workspace. If not set, will default to user's default workspace."
    required: false
  server:
    description: "Coiled server URL. If not set, will default to https://cloud.coiled.io ."
    required: false

runs:
    using: 'composite'
    steps:
      - uses: actions/checkout@v4
      - name: Install conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-downloads-key: coiled-login-downloads-${{ runner.arch }}
          cache-environment-key: coiled-login-env-${{ runner.arch }}
          generate-run-shell: false
          environment-name: coiled-login
          create-args: >-
            python=3.12
            coiled=1.45.0

      - name: Run coiled login
        shell: bash
        run: |
          if [[ -n "${{ inputs.server }}" ]] && [[ -n "${{ inputs.workspace }}" ]] &&; then
            coiled login --token ${{ inputs.token }} --workspace ${{ inputs.workspace }} --server ${{ inputs.server }}
          elif [[ -n "${{ inputs.server }}" ]]; then
            coiled login --token ${{ inputs.token }} --server ${{ inputs.server }}
          elif [[ -n "${{ inputs.workspace }}" ]]; then
            coiled login --token ${{ inputs.token }} --workspace ${{ inputs.workspace }}
          else
            coiled login --token ${{ inputs.token }}
          fi
