name: 'Coiled Login'
description: 'GitHub Action to login to Coiled'
author: 'Coiled'

branding:
  icon: 'log-in'
  color: 'blue'

inputs:
  token:
    description: "Coiled user API token. Required. You can create a token at https://cloud.coiled.io/profile?createTokenDialog=1"
    required: true
  workspace:
    description: "Coiled workspace. If not set, will default to user's default workspace."
    required: false
  server:
    description: "Coiled server URL. If not set, will default to https://cloud.coiled.io ."
    required: false

runs:
    using: 'composite'
    steps:
      - name: Check if token is set
        shell: bash
        run: |
          if [[ -z "${{ inputs.token }}" ]]; then
            echo "Token is required."
            exit 1
          fi
      - uses: actions/checkout@v4
      - name: Install conda environment
        uses: mamba-org/setup-micromamba@v1
        env:
          PYTHON_VERSION: 3.12
          COILED_VERSION: 1.45.0
        with:
          cache-downloads-key: coiled-login-downloads-${{ runner.arch }}-${{ envs.PYTHON_VERSION }}-${{ envs.COILED_VERSION }}
          cache-environment-key: coiled-login-env-${{ runner.arch }}-${{ envs.PYTHON_VERSION }}-${{ envs.COILED_VERSION }}
          generate-run-shell: false
          environment-name: coiled-login
          create-args: >-
            python=${{ envs.PYTHON_VERSION }}
            coiled=${{ envs.COILED_VERSION }}

      - name: Run coiled login
        shell: bash
        env:
          INPUT_SERVER: ${{ inputs.server }}
          INPUT_WORKSPACE: ${{ inputs.workspace }}
          INPUT_TOKEN: ${{ inputs.token }}
        run: |
          args=()
          for input in token server workspace; do
            var_name="INPUT_${input^^}"  # Convert input to uppercase
            var_name=$(echo "$var_name" | tr '-' '_')  # Replace '-' with '_'
            value="${!var_name}"  # Use variable indirection to get the value
            if [[ -n "$value" ]]; then
              args+=("--$input" "$value")
            fi
          done
          micromamba run -n coiled-run coiled login "${args[@]}"