name: coiled-login-action

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Coiled Login Action
        uses: ./
        with:
          token: ${{ secrets.PROD_TEST_BOT_TOKEN }}

